# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# this means to ignore newlines until "baseurl:"
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Spare Time Development Studio
subtitle: Art and Interactive Design
email: Isaac.bryce@outlook.com
description: Spare Time Development is a Independant Art and Design studio based out of New Zealand. Displaying a range of 2d and 3d digital and analog explorations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sparetimedev.co.nz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Spare_Time_Dev
github_username:  IsaacBryce
facebook_username: sparetimedev

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
